version: '3'
services:
# Python Development Environment
    python:
        image: marroyo777/datalab-py:0.1
        container_name: pydev
        volumes:
            - ./datalab-py/src:/src/python-env/development
            - ./DataLab-DB/data:/src/python-env/data
        ports:
            - "8008:8888"
        networks:
            - local
# Relational Database/Data Warehouse
    database:
        image: marroyo777/DataLab-DB:0.1
        container_name: db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "datalab"]
            interval: 5s
            retries: 5
        restart: always
        ports:
            - "5432:5432"
        networks:
            - local
# Client Application for Database Management
    pgadmin:
        image: dpage/pgadmin4:6.10
        container_name: pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@datalab.com
            - PGADMIN_DEFAULT_PASSWORD=dataanalytics
            - PGADMIN_LISTEN_PORT=80
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - "8080:80"
        networks:
            - local
# Business Intelligence/Dashboarding Tool
    dashboard:
        image: metabase/metabase
        container_name: dashboard
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
        volumes:
            - metabase-data:/metabase-data
        ports:
            - "3000:3000"
        networks:
            - local
networks:
    local:
volumes:
    pgadmin-data: 
    postgres-data: 
    metabase-data: 
