version: '3'
services:
# Python Development Environment
    python:
        image: marroyo777/datalab-py:0.1
        container_name: pydev
        volumes:
            - ./datalab-py/src:/src/python-env/development
            - ./DataLab-DB/data:/src/python-env/data
        ports:
            - "8008:8888"
        networks:
            - local
# Relational Database/Data Warehouse
    database:
        image: marroyo777/datalab-db:0.3
        container_name: db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "datalab", "-d", "datalab-db"]
            interval: 5s
            retries: 5
        restart: always
        ports:
            - "5432:5432"
        networks:
            - local
# Client Application for Database Management
    dbadmin:
        image: marroyo777/datalab-dbadmin:0.1
        container_name: dbadmin
        restart: always
        volumes:
            - dbadmin-data:/var/lib/pgadmin
        ports:
            - "8080:80"
        networks:
            - local
# Business Intelligence/Dashboarding Tool
    dashboard:
        image: metabase/metabase
        container_name: dashboard
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
        volumes:
            - metabase-data:/metabase-data
        ports:
            - "3000:3000"
        networks:
            - local
networks:
    local:
volumes:
    dbadmin-data: 
    postgres-data: 
    metabase-data: 
